baseURL = "https://devopspatterns.github.io/"
languageCode = "en-us"
title = "DevOps Patterns"
theme = "hugo-theme-learn"
publishDir = "docs"
disableSearch = true
editURL = "https://github.com/devopspatterns/devopspatterns.github.io/edit/master/content/"

[params]
themeVariant = "devops"

[outputs]
home = ["HTML", "RSS", "JSON"]

