# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: run Hugo
      run: |
        docker run --rm -v $(pwd):/src klakegg/hugo:0.74.2-alpine
        ls -la

    # Runs a set of commands using the runners shell
    - name: Checkin changes to Hugo files (/docs) for publication
      run: |
        git config user.name emcconne
        git config user.email junk@masteringserverless.com
        git add docs
        git commit -m "Updated github pages"
        git push
